Repository RAF-SI-2023/Banka-4-Backend, pull requests merged in 2024-07, with the labels that each got.

#249 Jun
  user-service/src/main/java/rs/edu/raf/mapper/RadnikMapper.java
Labels: size/XS, lgtm, approved

#250 Cucumber testovi
  banka-service/src/main/java/rs/edu/raf/model/dto/RadnikDTO.java
  banka-service/src/test/java/rs/edu/raf/integration/account/AccountManagementConfig.java
  banka-service/src/test/java/rs/edu/raf/integration/account/AccountManagementTests.java
  banka-service/src/test/java/rs/edu/raf/integration/account/AccountManagementTestsSteps.java
  banka-service/src/test/resources/feature/account/accountmanagement.feature
Labels: lgtm, size/L, approved, ¯\_(ツ)_/¯

#251 Testovi
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderRequest.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
  berza-servis/src/test/java/rs/edu/raf/order/service/impl/OrderServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/order/service/mapper/OrderMapperTest.java
Labels: lgtm, size/L, approved

#252 Jun
  banka-service/src/main/java/rs/edu/raf/security/SpringSecurityConfig.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/AtmDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/UserStockDto.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/UserStockMapper.java
Labels: size/M, lgtm, approved

#253 Jun
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: size/XS, lgtm, approved

#254 Jun
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: size/XS, lgtm, approved

#255 ruta fix
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: size/M, lgtm, approved

#256 Jun
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: lgtm, size/S, approved

#257 Jun
  berza-servis/src/main/java/rs/edu/raf/order/repository/BankOTCStockRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: lgtm, size/S, approved

#258 Unit testovi za OTC unutar banke
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
  berza-servis/src/test/java/rs/edu/raf/otc_unutar_banke/OTCUnitTest.java
Labels: lgtm, size/L, approved

#259 Jun
  berza-servis/src/main/java/rs/edu/raf/order/repository/OTCRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/UserStockServiceImpl.java
Labels: size/M, lgtm, approved

#260 Jun
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
Labels: size/XS, lgtm, approved
