Repository RAF-SI-2023/Banka-4-Backend, pull requests merged in 2024-06, with the labels that each got.

#157 Update build.yaml
  .prow/build.yaml
Labels: size/XS

#158 Update README.md
  README.md
Labels: size/XS, lgtm, approved

#159 Update RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
Labels: lgtm, size/L, approved

#160 Petar stamenic patch 5
  .prow/build.yaml
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/M, lgtm, approved

#161 Update Seeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#164 @Disabled je bio na user testovima
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/Firma.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/NegativeIdGenerator.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/controller/OrderController.java
  berza-servis/src/main/java/rs/edu/raf/order/controller/PonudaController.java
  berza-servis/src/main/java/rs/edu/raf/order/controller/UserStockController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/Banka3StockDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/PonudaDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/RadnikDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Ponuda.java
  berza-servis/src/main/java/rs/edu/raf/order/model/StranaPonudaDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/PonudaRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/service/PonudaService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/PonudaServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/PonudaMapper.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/UserStockMapper.java
  berza-servis/src/main/java/rs/edu/raf/security/SpringSecurityConfig.java
  user-service/src/main/java/rs/edu/raf/controller/RadnikController.java
  user-service/src/main/java/rs/edu/raf/servis/KorisnikServis.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
  user-service/src/test/java/rs/edu/raf/korisnik/integration/service/UserServiceTests.java
  user-service/src/test/java/rs/edu/raf/korisnik/integration/service/UserServiceTestsSteps.java
Labels: size/XXL, lgtm, approved

#165 Update RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
Labels: size/M, lgtm, size/S, approved

#166 Update RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
Labels: size/M, lgtm, approved

#167 Update Seeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#168 Update Seeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#169 Update RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
Labels: size/XS, lgtm, approved

#170 Update Seeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
  user-service/src/test/java/rs/edu/raf/mail/MailTest.java
Labels: lgtm, size/S, approved

#171 Update README.md
  README.md
Labels: size/XS, lgtm, approved

#173 Update Seeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#172 Sprint 6
  banka-4.iml
  berza-servis/berza-servis.iml
  berza-servis/src/main/java/rs/edu/raf/order/controller/OrderController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderDto.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OrderService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
Labels: lgtm, size/L, approved

#175 Sprint 6
  banka-service/src/main/java/rs/edu/raf/model/entities/transaction/MarznaTransakcija.java
  banka-service/src/main/java/rs/edu/raf/model/entities/transaction/OpisTransakcije.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/MarznaTransakcijaRepository.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
  banka-service/src/test/java/rs/edu/raf/racun/MarzniRacunServiceImplTest.java
  banka-service/src/test/java/rs/edu/raf/racun/mapper/MarzniRacunMapperTest.java
Labels: lgtm, size/L, approved

#179 Scheduled methods for future contracts and fixes
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  berza-servis/src/main/java/rs/edu/raf/futures/controller/FuturesController.java
  berza-servis/src/main/java/rs/edu/raf/futures/model/FuturesContract.java
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FutureContractRequestRepository.java
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FuturesContractRepository.java
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/model/StranaPonudaDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/PonudaRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/PonudaServiceImpl.java
  init-db.sql
  user-service/src/main/java/rs/edu/raf/repository/RadnikRepository.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
Labels: size/XL, lgtm, approved

#178 valjda radi web socket
  banka-4.iml
  banka-service/banka-servis.iml
  banka-service/src/main/java/rs/edu/raf/configuration/WebSocketConfig.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  berza-servis/berza-servis.iml
Labels: size/M, lgtm, approved

#180 Some fixes
  berza-servis/src/main/java/rs/edu/raf/order/controller/PonudaController.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
Labels: size/XS, lgtm, approved

#181 Porez drzave na prodaju stockova i profit banke od prodaje stockova.
  banka-service/src/main/java/rs/edu/raf/controller/racun/MarzniRacunController.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunService.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
Labels: lgtm, size/S, approved

#182 Future contract fix
  berza-servis/src/main/java/rs/edu/raf/futures/dto/FutureRequestDto.java
  berza-servis/src/main/java/rs/edu/raf/futures/dto/FuturesContractDto.java
  berza-servis/src/main/java/rs/edu/raf/futures/mapper/FuturesContractMapper.java
Labels: size/XS, lgtm, approved

#183 Dodata mogucnost kupovine opcije za korisnika
  berza-servis/src/main/java/rs/edu/raf/opcija/controller/OpcijaController.java
  berza-servis/src/main/java/rs/edu/raf/opcija/dto/NovaOpcijaDto.java
  berza-servis/src/main/java/rs/edu/raf/opcija/dto/OpcijaKorisnikaDto.java
  berza-servis/src/main/java/rs/edu/raf/opcija/mapper/OpcijaMapper.java
  berza-servis/src/main/java/rs/edu/raf/opcija/model/KorisnikoveKupljeneOpcije.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/OpcijaServis.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/impl/OpcijaServisImpl.java
Labels: size/M, lgtm, approved

#184 Update KorisnikServisImpl.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
Labels: size/XS, lgtm, approved

#185 Seeders fix
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FutureSeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
Labels: size/XS, lgtm, approved

#187 Update ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
Labels: lgtm, size/S, approved

#189 Fin
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  berza-servis/src/main/java/rs/edu/raf/futures/model/FuturesContract.java
Labels: lgtm, size/S, approved

#188 Update RacunServisImpl.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
Labels: size/XS, lgtm, approved

#192 Fin
  berza-servis/src/main/java/rs/edu/raf/futures/controller/FuturesController.java
Labels: size/XS, lgtm, approved

#190 Update RacunServisImpl.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
Labels: size/XS, lgtm, approved

#193 Prepravka za vracanje kartica i kredita
  banka-service/src/main/java/rs/edu/raf/model/mapper/CardMapper.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/repository/CardRepository.java
  banka-service/src/main/java/rs/edu/raf/repository/CreditRequestRepository.java
  banka-service/src/main/java/rs/edu/raf/service/CardServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/impl/CurrencyServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/CSVSeeder.java
  berza-servis/src/main/resources/application.properties
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: lgtm, size/S, approved

#196 Finfin
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/PonudaServiceImpl.java
Labels: size/XS, lgtm, approved

#197 Update README.md
  README.md
Labels: size/XS, lgtm, approved

#198 Finfin
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/CSVSeeder.java
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FutureSeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTests.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTestsConfig.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTestsSteps.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XXL, lgtm, approved

#199 Update Seeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#200 Future contract fix
  berza-servis/src/main/java/rs/edu/raf/futures/controller/FuturesController.java
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesService.java
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesServiceImpl.java
Labels: size/M, lgtm, approved

#201 Seeder fix
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FutureSeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
Labels: lgtm, size/L, approved

#202 Seeder fix
  berza-servis/src/main/java/rs/edu/raf/futures/mapper/FuturesContractMapper.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: lgtm, size/L, approved

#204 Revert "Update Seeder.java"
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#209 Dodat userId u OrderDto
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderDto.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
Labels: size/XS, lgtm, approved

#207 Dev4
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderDto.java
  berza-servis/src/test/java/rs/edu/raf/e2e/opcijacontroller/OpcijaControllerTests.java
  berza-servis/src/test/java/rs/edu/raf/e2e/opcijacontroller/OpcijaControllerTestsConfig.java
  berza-servis/src/test/java/rs/edu/raf/e2e/opcijacontroller/OpcijaControllerTestsSteps.java
Labels: lgtm, size/L, approved

#210 ajmo i mi da testiramo ko druge banke :)
  banka-service/pom.xml
  berza-servis/pom.xml
  user-service/pom.xml
Labels: size/M, lgtm, approved

#211 trying test annotations
  banka-service/pom.xml
  banka-service/src/main/java/rs/edu/raf/annotations/Generated.java
  banka-service/src/main/java/rs/edu/raf/annotations/GeneratedCrudOperation.java
  banka-service/src/main/java/rs/edu/raf/annotations/GeneratedExternalAPI.java
  banka-service/src/main/java/rs/edu/raf/annotations/GeneratedLegacyCode.java
  banka-service/src/main/java/rs/edu/raf/annotations/GeneratedOnlyIntegrationTestable.java
  banka-service/src/main/java/rs/edu/raf/annotations/GeneratedScheduledOperation.java
  banka-service/src/main/java/rs/edu/raf/service/CreditServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/TransakcijaServis.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/annotations/Generated.java
  berza-servis/src/main/java/rs/edu/raf/annotations/GeneratedCrudOperation.java
  berza-servis/src/main/java/rs/edu/raf/annotations/GeneratedExternalAPI.java
  berza-servis/src/main/java/rs/edu/raf/annotations/GeneratedLegacyCode.java
  berza-servis/src/main/java/rs/edu/raf/annotations/GeneratedOnlyIntegrationTestable.java
  berza-servis/src/main/java/rs/edu/raf/annotations/GeneratedScheduledOperation.java
  user-service/src/main/java/rs/edu/raf/annotations/Generated.java
  user-service/src/main/java/rs/edu/raf/annotations/GeneratedCrudOperation.java
  user-service/src/main/java/rs/edu/raf/annotations/GeneratedExternalAPI.java
  user-service/src/main/java/rs/edu/raf/annotations/GeneratedLegacyCode.java
  user-service/src/main/java/rs/edu/raf/annotations/GeneratedOnlyIntegrationTestable.java
  user-service/src/main/java/rs/edu/raf/annotations/GeneratedScheduledOperation.java
Labels: lgtm, approved

#213 seeders
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/CSVSeeder.java
Labels: size/XXL, lgtm, approved

#214 Update RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
Labels: lgtm, approved

#215 Dohvatanje opcija korisnika po id implementirano.
  berza-servis/src/main/java/rs/edu/raf/opcija/controller/OpcijaController.java
  berza-servis/src/main/java/rs/edu/raf/opcija/mapper/OpcijaMapper.java
  berza-servis/src/main/java/rs/edu/raf/opcija/repository/KorisnikoveKupljeneOpcijeRepository.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/OpcijaServis.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/impl/OpcijaServisImpl.java
Labels: size/M, lgtm, approved

#216 Dohvatanje firmi po id za front implementirano.
  banka-service/src/main/java/rs/edu/raf/controller/racun/RacunController.java
  banka-service/src/main/java/rs/edu/raf/service/racun/RacunServis.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
Labels: lgtm, size/S, approved

#219 OTC exception za izbegavanje dve ponude u isto vreme dodat.
  berza-servis/src/main/java/rs/edu/raf/order/controller/OTCController.java
  berza-servis/src/main/java/rs/edu/raf/order/exceptions/OTCOfferCurrentlyPlaced.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/stocks/exceptions/ErrorCode.java
Labels: lgtm, size/S, approved

#221 otc
  berza-servis/src/main/java/rs/edu/raf/order/controller/BankOtcController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/banka3/FrontendOfferDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/banka3/MyOfferDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/banka3/MyStockDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/banka3/OfferDto.java
  berza-servis/src/main/java/rs/edu/raf/order/model/BankOTCStock.java
  berza-servis/src/main/java/rs/edu/raf/order/model/MyOffer.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Offer.java
  berza-servis/src/main/java/rs/edu/raf/order/model/OfferStatus.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/BankOTCStockRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/MyOfferRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/OfferRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
  berza-servis/src/main/java/rs/edu/raf/security/SpringSecurityConfig.java
Labels: size/XL, lgtm, approved

#222 otc fix
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
Labels: size/XS, lgtm, approved

#223 Jun
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
Labels: size/XS, lgtm, approved

#224 Jun
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
Labels: lgtm, size/L, approved

#225 Jun
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/CSVSeeder.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#226 Jun
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XS, lgtm, approved

#227 Unit tests for user service, bug fixes
  berza-servis/src/main/java/rs/edu/raf/futures/controller/FuturesController.java
  berza-servis/src/main/java/rs/edu/raf/futures/mapper/FuturesContractMapper.java
  berza-servis/src/main/java/rs/edu/raf/futures/repository/FutureContractRequestRepository.java
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KodServisImpl.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
  user-service/src/main/java/rs/edu/raf/servis/impl/OmiljeniKorisnikServisImpl.java
  user-service/src/main/java/rs/edu/raf/servis/impl/SifrePlacanjaServisImpl.java
  user-service/src/test/java/rs/edu/raf/korisnik/KodServisUnitTests.java
  user-service/src/test/java/rs/edu/raf/oneTimePassword/UnitTests.java
Labels: lgtm, size/L, approved

#228 Unit tests
  banka-service/src/main/java/rs/edu/raf/BankaSpringBootApplication.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/BerzaServosSpringBootApplication.java
  berza-servis/src/main/java/rs/edu/raf/exchange/service/implementation/ExchangeServiceImplementation.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/impl/OpcijaServisImpl.java
  berza-servis/src/test/java/rs/edu/raf/exchange/service/ExchangeServiceTest.java
  user-service/src/main/java/rs/edu/raf/UserBackendSpringBootApplication.java
  user-service/src/main/java/rs/edu/raf/servis/impl/MailServiceImplementation.java
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
Labels: lgtm, size/L, approved

#229 Bug fixes
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
Labels: lgtm, size/S, approved

#230 Sprint 6
  berza-servis/src/main/java/rs/edu/raf/order/controller/OrderController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderRequest.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/UserStockDto.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Order.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OrderService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/UserStockMapper.java
  user-service/src/main/java/rs/edu/raf/controller/RadnikController.java
  user-service/src/main/java/rs/edu/raf/model/Radnik.java
  user-service/src/main/java/rs/edu/raf/servis/KorisnikServis.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
Labels: size/M, lgtm, approved

#231 Bug fixes, unit tests
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OTCDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/seeder/UserStockRepositorySeeder.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OTCMapper.java
  user-service/src/main/java/rs/edu/raf/controller/RadnikController.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
Labels: lgtm, size/L, approved

#232 OTC unutar banke fix
  berza-servis/src/main/java/rs/edu/raf/order/controller/OTCController.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OTCService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
Labels: lgtm, size/S, approved

#233 unit tests, otc fixed
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/BankOtcService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/PonudaServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/UserStockServiceImpl.java
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
Labels: lgtm, size/L, approved

#234 Update pom.xml
  berza-servis/pom.xml
Labels: size/XS, lgtm, approved

#235 Update pom.xml
  berza-servis/pom.xml
Labels: size/XS, lgtm, approved

#237 Dodati jos neki testovi
  banka-service/src/test/java/rs/edu/raf/service/CardServiceImplTest.java
  banka-service/src/test/java/rs/edu/raf/service/CreditServiceImplTest.java
Labels: lgtm, size/L, approved

#238 Order bugfix
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/impl/OpcijaServisImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
Labels: size/XS, lgtm, approved

#240 Prethodni PR bez izlistavanja racuna firme
  banka-service/src/main/java/rs/edu/raf/model/mapper/racun/RacunMapper.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
  banka-service/src/test/java/rs/edu/raf/racun/mapper/RacunMapperTests.java
  banka-service/src/test/java/rs/edu/raf/service/transaction/impl/RacunServisImplTests.java
  banka-service/src/test/resources/feature/account/accountmanagement.feature
Labels: lgtm, size/L, approved

#244 Opcija fix
  berza-servis/src/main/java/rs/edu/raf/opcija/dto/OpcijaKorisnikaDto.java
  berza-servis/src/main/java/rs/edu/raf/opcija/mapper/OpcijaMapper.java
  berza-servis/src/main/java/rs/edu/raf/opcija/model/KorisnikoveKupljeneOpcije.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
Labels: lgtm, size/S, approved

#245 Otc unutar banke
  berza-servis/src/main/java/rs/edu/raf/order/controller/OTCController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OTCDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OTCOfferDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OTCPlaceDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OTCResolveDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/PublicUserStockDto.java
  berza-servis/src/main/java/rs/edu/raf/order/model/OTC.java
  berza-servis/src/main/java/rs/edu/raf/order/model/UserStock.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/OTCRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OTCService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/UserStockService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OTCServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/UserStockServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OTCMapper.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/PublicUserStockMapper.java
  berza-servis/src/test/java/rs/edu/raf/otc/integration/OTCControllerTestsSteps.java
  user-service/src/main/java/rs/edu/raf/controller/RadnikController.java
Labels: size/XL, lgtm, approved
