Repository RAF-SI-2023/Banka-4-Backend, pull requests merged in 2024-04, with the labels that each got.

#73 Sprint 4
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/currency/controller/CurrencyController.java
  berza-servis/src/main/java/rs/edu/raf/currency/controller/InflationController.java
  berza-servis/src/main/java/rs/edu/raf/currency/dto/CurrencyDTO.java
  berza-servis/src/main/java/rs/edu/raf/currency/dto/InflationDTO.java
  berza-servis/src/main/java/rs/edu/raf/currency/mapper/CurrencyMapper.java
  berza-servis/src/main/java/rs/edu/raf/currency/mapper/InflationMapper.java
  berza-servis/src/main/java/rs/edu/raf/currency/model/Currency.java
  berza-servis/src/main/java/rs/edu/raf/currency/model/Inflation.java
  berza-servis/src/main/java/rs/edu/raf/currency/model/InflationId.java
  berza-servis/src/main/java/rs/edu/raf/currency/repository/CurrencyRepository.java
  berza-servis/src/main/java/rs/edu/raf/currency/repository/InflationRepository.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/CurrencyService.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/InflationService.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/impl/CurrencyServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/impl/InflationServiceImpl.java
  berza-servis/src/test/java/rs/edu/raf/currency/service/impl/CurrencyServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/currency/service/impl/InflationServiceImplTest.java
  user-service/user-service.iml
Labels: size/XL

#74 some things have been changed
  banka-service/banka-servis.iml
  banka-service/pom.xml
  banka-service/src/main/java/rs/edu/raf/model/mapper/CreditRequestMapper.java
  berza-servis/pom.xml
  user-service/src/main/java/rs/edu/raf/dto/NoviKorisnikDTO.java
  user-service/src/main/java/rs/edu/raf/dto/NoviRadnikDTO.java
  user-service/src/main/java/rs/edu/raf/dto/OmiljeniKorisnikDTO.java
  user-service/src/main/java/rs/edu/raf/mapper/OmiljeniKorisnikMapper.java
  user-service/src/main/java/rs/edu/raf/model/OmiljeniKorisnik.java
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
  user-service/src/test/java/rs/edu/raf/korisnik/servis/impl/OmiljeniKorisnikServisImplTest.java
Labels: size/M

#75 Integracija i cuvanje podataka o berzama #51
  banka-4.iml
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/exchange/controller/ExchangeController.java
  berza-servis/src/main/java/rs/edu/raf/exchange/dto/ExchangeDTO.java
  berza-servis/src/main/java/rs/edu/raf/exchange/dto/ExchangeWorkingHoursDTO.java
  berza-servis/src/main/java/rs/edu/raf/exchange/mapper/ExchangeMapper.java
  berza-servis/src/main/java/rs/edu/raf/exchange/mapper/ExchangeWorkingHoursMapper.java
  berza-servis/src/main/java/rs/edu/raf/exchange/model/Exchange.java
  berza-servis/src/main/java/rs/edu/raf/exchange/model/ExchangeWorkingHours.java
  berza-servis/src/main/java/rs/edu/raf/exchange/repository/ExchangeRepository.java
  berza-servis/src/main/java/rs/edu/raf/exchange/repository/ExchangeWorkingHoursRepository.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/CSVSeeder.java
  berza-servis/src/main/java/rs/edu/raf/exchange/seeder/HolidaysSeeder.java
  berza-servis/src/main/java/rs/edu/raf/exchange/service/ExchangeService.java
  berza-servis/src/main/java/rs/edu/raf/exchange/service/implementation/ExchangeServiceImplementation.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTests.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTestsConfig.java
  berza-servis/src/test/java/rs/edu/raf/exchange/integration/ExchangeControllerTestsSteps.java
  berza-servis/src/test/java/rs/edu/raf/exchange/mapper/ExchangeMapperTest.java
  berza-servis/src/test/java/rs/edu/raf/exchange/mapper/ExchangeWorkingHoursMapperTest.java
  berza-servis/src/test/java/rs/edu/raf/exchange/service/ExchangeServiceTest.java
  berza-servis/src/test/resources/features/integration/exchange_endpoints.feature
Labels: size/XXL

#76 Integracioni testovi za stock service i controller odradjeni.
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/stocks/StockServiceImpl.java
  berza-servis/src/test/java/rs/edu/raf/currency/service/CurrencyServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/currency/service/InflationServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/controller/StocksControllerConfig.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/controller/StocksControllerTests.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/controller/StocksControllerTestsSteps.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/service/StocksServiceConfig.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/service/StocksServiceTests.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/service/StocksServiceTestsSteps.java
  berza-servis/src/test/java/rs/edu/raf/stocks/unit/service/StockServiceImplUnitTests.java
  berza-servis/src/test/resources/features/stocks.integration.service/stocksservice.feature
  berza-servis/src/test/resources/features/stocks/integration/controller/stockscontroller.feature
  berza-servis/src/test/resources/junit-platform.properties
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
Labels: size/XL

#77 Sprint 2
  banka-service/banka-servis.iml
  banka-service/pom.xml
  banka-service/src/main/java/rs/edu/raf/model/mapper/CreditRequestMapper.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/TransakcijaServis.java
  berza-servis/pom.xml
  berza-servis/src/main/java/rs/edu/raf/order/controller/OrderController.java
  berza-servis/src/main/java/rs/edu/raf/order/controller/UserStockController.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/OrderRequest.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/UserDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/UserStockDto.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/UserStockRequest.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Enums/Action.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Enums/Status.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Enums/Type.java
  berza-servis/src/main/java/rs/edu/raf/order/model/Order.java
  berza-servis/src/main/java/rs/edu/raf/order/model/UserStock.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/OrderRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/repository/UserStockRepository.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OrderService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/UserStockService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/UserStockServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/OrderMapper.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/UserStockMapper.java
  user-service/pom.xml
  user-service/src/main/java/rs/edu/raf/dto/NoviKorisnikDTO.java
  user-service/src/main/java/rs/edu/raf/dto/NoviRadnikDTO.java
  user-service/src/main/java/rs/edu/raf/dto/OmiljeniKorisnikDTO.java
  user-service/src/main/java/rs/edu/raf/mapper/OmiljeniKorisnikMapper.java
  user-service/src/main/java/rs/edu/raf/model/OmiljeniKorisnik.java
  user-service/src/main/resources/application.properties
  user-service/src/test/java/rs/edu/raf/korisnik/KorisnikServisUnitTests.java
  user-service/src/test/java/rs/edu/raf/korisnik/servis/impl/OmiljeniKorisnikServisImplTest.java
Labels: size/XXL

#88 Merge dev4 with main
  banka-service/src/main/java/rs/edu/raf/configuration/WebSocketConfig.java
  banka-service/src/main/java/rs/edu/raf/service/CardServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/CreditServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  banka-service/src/main/resources/application.properties
  banka-service/src/test/java/rs/edu/raf/realizacijaTransakcija/TransakcijaServisImplTest.java
  banka-service/src/test/java/rs/edu/raf/servis/impl/TransakcijaServisImplTest.java
  berza-servis/src/main/resources/application.properties
  berza-servis/src/test/java/OpcijaServisIntegationTest.java
  berza-servis/src/test/java/rs/edu/raf/exchange/service/ExchangeServiceTest.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/controller/StocksControllerTests.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/service/StocksServiceTests.java
  docker-compose.yml
  user-service/src/main/resources/application.properties
Labels: size/XL

#90 Documentation
  banka-service/src/main/java/rs/edu/raf/service/CardService.java
  banka-service/src/main/java/rs/edu/raf/service/CreditService.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateService.java
  banka-service/src/main/java/rs/edu/raf/service/racun/RacunServis.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/TransakcijaServis.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/CurrencyService.java
  berza-servis/src/main/java/rs/edu/raf/currency/servis/InflationService.java
  berza-servis/src/main/java/rs/edu/raf/exchange/service/ExchangeService.java
  berza-servis/src/main/java/rs/edu/raf/futures/service/FuturesService.java
  berza-servis/src/main/java/rs/edu/raf/opcija/servis/OpcijaServis.java
  berza-servis/src/main/java/rs/edu/raf/order/service/OrderService.java
  berza-servis/src/main/java/rs/edu/raf/order/service/UserStockService.java
  berza-servis/src/main/java/rs/edu/raf/stocks/service/StockService.java
  berza-servis/src/test/java/rs/edu/raf/stocks/unit/service/StockServiceImplUnitTests.java
  user-service/src/main/java/rs/edu/raf/controller/OneTimePasswordController.java
  user-service/src/main/java/rs/edu/raf/servis/KodServis.java
  user-service/src/main/java/rs/edu/raf/servis/KorisnikServis.java
  user-service/src/main/java/rs/edu/raf/servis/MailServis.java
  user-service/src/main/java/rs/edu/raf/servis/OmiljeniKorisnikServis.java
  user-service/src/main/java/rs/edu/raf/servis/OneTimePasswordService.java
  user-service/src/main/java/rs/edu/raf/servis/SifrePlacanjaServis.java
  user-service/src/main/java/rs/edu/raf/servis/impl/OneTimePasswordServiceImpl.java
  user-service/src/test/java/rs/edu/raf/oneTimePassword/IntegrationTests.java
Labels: size/XXL

#86 Odradjeni testovi za Ordere
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/mapper/UserStockMapper.java
  berza-servis/src/test/java/rs/edu/raf/order/service/impl/OrderServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/order/service/impl/UserStockServiceImplTest.java
  berza-servis/src/test/java/rs/edu/raf/order/service/mapper/OrderMapperTest.java
  berza-servis/src/test/java/rs/edu/raf/order/service/mapper/UserStockMapperTest.java
Labels: size/L

#96 Nesto sam us....
  banka-service/src/main/java/rs/edu/raf/configuration/MyConfiguration.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  banka-service/src/main/resources/application.properties
  berza-servis/src/main/resources/application.properties
  berza-servis/src/test/java/rs/edu/raf/stocks/unit/service/StockServiceImplUnitTests.java
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
  user-service/src/main/resources/application.properties
  user-service/src/test/java/rs/edu/raf/korisnik/integration/service/UserServiceTests.java
  user-service/src/test/java/rs/edu/raf/korisnik/integration/service/UserServiceTestsSteps.java
Labels: approved

#98 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved

#110 Update OWNERS
  OWNERS
Labels: size/XS, lgtm, approved
