Repository RAF-SI-2023/Banka-4-Backend, pull requests merged in 2024-05, with the labels that each got.

#122 CD
  .prow/build.yaml
  banka-service/Dockerfile
  berza-servis/Dockerfile
  user-service/Dockerfile
Labels: size/M, lgtm, approved

#124 Update build.yaml
  .prow/build.yaml
Labels: size/XS, lgtm, approved

#125 Update build.yaml
  .prow/build.yaml
Labels: size/XS

#128 Update README.md - TEST CI/CD
  README.md
Labels: size/XS, lgtm, approved

#120 Marzni Racun gotov
  banka-service/src/main/java/rs/edu/raf/controller/racun/MarzniRacunController.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunCreateDTO.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunDTO.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunUpdateDTO.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/MarzniRacun.java
  banka-service/src/main/java/rs/edu/raf/model/mapper/racun/MarzniRacunMapper.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/MarzniRacunRepository.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunService.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
Labels: lgtm, size/L, approved

#129 Marzni Racun gotov (#120)
  banka-service/src/main/java/rs/edu/raf/controller/racun/MarzniRacunController.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunCreateDTO.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunDTO.java
  banka-service/src/main/java/rs/edu/raf/model/dto/racun/MarzniRacunUpdateDTO.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/MarzniRacun.java
  banka-service/src/main/java/rs/edu/raf/model/mapper/racun/MarzniRacunMapper.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/MarzniRacunRepository.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunService.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
Labels: lgtm, size/L, approved

#131 Adding currencies and invoices
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/ExchangeAccount.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/ExchangeInvoice.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/repository/racun/ExchangeAccountRepository.java
  banka-service/src/main/java/rs/edu/raf/repository/racun/InvoiceRepository.java
Labels: size/XL, lgtm, approved

#139 Dodati su (integracioni, unit) i promenjeni seeder fajlovi
  banka-service/pom.xml
  banka-service/src/main/java/rs/edu/raf/controller/CardController.java
  banka-service/src/main/java/rs/edu/raf/controller/CreditController.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/service/CardServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/CreditService.java
  banka-service/src/main/java/rs/edu/raf/service/CreditServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  banka-service/src/test/java/rs/edu/raf/integration/card/CardManagementTests.java
  banka-service/src/test/java/rs/edu/raf/integration/card/CardManagementTestsConfig.java
  banka-service/src/test/java/rs/edu/raf/integration/card/CardManagementTestsSteps.java
  banka-service/src/test/java/rs/edu/raf/integration/credit/CreditManagementConfig.java
  banka-service/src/test/java/rs/edu/raf/integration/credit/CreditManagementTestSteps.java
  banka-service/src/test/java/rs/edu/raf/integration/credit/CreditManagementTests.java
  banka-service/src/test/java/rs/edu/raf/service/CardServiceImplTest.java
  banka-service/src/test/java/rs/edu/raf/service/CreditServiceImplTest.java
  banka-service/src/test/java/rs/edu/raf/service/ExchangeRateServiceImplTest.java
  banka-service/src/test/resources/feature/card/cardmanagement.feature
  banka-service/src/test/resources/feature/credit/creditmanagement.feature
  banka-service/src/test/resources/junit-platform.properties
  user-service/src/main/java/rs/edu/raf/repository/Seeder.java
Labels: size/XXL, lgtm, approved

#140 racun apstrakcija, realizovanje transakcija u sql
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/DevizniRacun.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/PravniRacun.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/Racun.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/TekuciRacun.java
  banka-service/src/main/java/rs/edu/raf/model/mapper/racun/RacunMapper.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/RacunSeeder.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/RacunRepository.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/SablonTransakcijeRepository.java
  banka-service/src/main/java/rs/edu/raf/service/ExchangeRateServiceImpl.java
  banka-service/src/main/java/rs/edu/raf/service/racun/impl/RacunServisImpl.java
  banka-service/src/main/java/rs/edu/raf/service/transaction/impl/TransakcijaServisImpl.java
  banka-service/src/test/java/rs/edu/raf/racun/mapper/RacunMapperTests.java
  banka-service/src/test/java/rs/edu/raf/realizacijaTransakcija/TransakcijaServisImplTest.java
  banka-service/src/test/java/rs/edu/raf/service/transaction/impl/RacunServisImplTests.java
  banka-service/src/test/java/rs/edu/raf/servis/impl/TransakcijaServisImplTest.java
Labels: size/XXL, lgtm, approved

#142 Revert "please"
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/ExchangeAccount.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/ExchangeInvoice.java
  banka-service/src/main/java/rs/edu/raf/racun/seeder/ExchangeAccountSeeder.java
  banka-service/src/main/java/rs/edu/raf/repository/racun/ExchangeAccountRepository.java
  banka-service/src/main/java/rs/edu/raf/repository/racun/InvoiceRepository.java
Labels: lgtm, size/L, approved

#150 Bug fix adding account to user
  user-service/src/main/java/rs/edu/raf/servis/impl/KorisnikServisImpl.java
Labels: size/XS, lgtm, approved

#152 Update init-db.sql
  init-db.sql
Labels: lgtm, size/L, approved

#155 Margin call implementacija i test kroz End2end integracioni test plus End2end za Stock Controller.
  banka-service/pom.xml
  banka-service/src/main/java/rs/edu/raf/controller/racun/MarzniRacunController.java
  banka-service/src/main/java/rs/edu/raf/exceptions/ErrorCode.java
  banka-service/src/main/java/rs/edu/raf/exceptions/InsufficientAmountOfStockException.java
  banka-service/src/main/java/rs/edu/raf/exceptions/StockForUsersMarginAccountException.java
  banka-service/src/main/java/rs/edu/raf/model/dto/PairDTO.java
  banka-service/src/main/java/rs/edu/raf/model/entities/racun/MarzniRacun.java
  banka-service/src/main/java/rs/edu/raf/model/mapper/racun/MarzniRacunMapper.java
  banka-service/src/main/java/rs/edu/raf/request/OrderRequest.java
  banka-service/src/main/java/rs/edu/raf/response/OrderResponse.java
  banka-service/src/main/java/rs/edu/raf/response/UserStockDTOResponse.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunService.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
  banka-service/src/test/java/rs/edu/raf/racun/marzni/integration/controller/MarzniRacunControllerConfig.java
  banka-service/src/test/java/rs/edu/raf/racun/marzni/integration/controller/MarzniRacunControllerTests.java
  banka-service/src/test/java/rs/edu/raf/racun/marzni/integration/controller/MarzniRacunControllerTestsSteps.java
  banka-service/src/test/resources/feature/racun/integration/controller/marzniracuncontroller.feature
  berza-servis/src/main/java/rs/edu/raf/config/RedisConfiguration.java
  berza-servis/src/main/java/rs/edu/raf/order/dto/PairDTO.java
  berza-servis/src/main/java/rs/edu/raf/order/service/impl/OrderServiceImpl.java
  berza-servis/src/main/java/rs/edu/raf/stocks/exceptions/ExceptionResponse.java
  berza-servis/src/test/java/rs/edu/raf/stocks/integration/controller/StocksControllerTestsSteps.java
  berza-servis/src/test/resources/features/stocks/integration/controller/stockscontroller.feature
  user-service/src/test/java/rs/edu/raf/korisnik/integration/service/UserServiceConfig.java
Labels: size/XXL, lgtm, approved

#156 dopuna margin calla - uplata na marzni racun
  banka-service/src/main/java/rs/edu/raf/controller/racun/MarzniRacunController.java
  banka-service/src/main/java/rs/edu/raf/repository/transaction/MarzniRacunRepository.java
  banka-service/src/main/java/rs/edu/raf/service/MarzniRacunServiceImpl.java
Labels: lgtm, size/S, approved
